# Site settings
title: Nick Whyte
email: nick@nickwhyte.com
description: Programming and Exciting Things
gravatar: http://www.gravatar.com/avatar/5986012fd232ca94685904a95c56b17e
copyright: '&copy; Nick Whyte 2014'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nickwhyte.com" # the base hostname & protocol for your site
twitter_username: nickw444
github_username:  nickw444
paginate: 5
paginate_path: "/:num"
permalink: '/post/:year/:title/'
# Build settings
markdown: kramdown
include: ['_pages']